parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.6'
        charset: utf8mb4
        host: '%env(DATABASE_HOST)%'
        port: '3306'
        user: '%env(DATABASE_USER)%'
        password: '%env(DATABASE_PASSWORD)%'
        dbname: '%env(DATABASE_NAME)%'
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
        types:
            codebreaker_code: App\Type\CodeType
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            Codebreaker:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/src/App/Entity'
                prefix: 'PcComponentes\Codebreaker'
                alias: Codebreaker
